package enums;

public enum DIN8580 {
	Putzen_oder_Verputzen, Anstreichen_oder_Lackieren, Beschichten_durch_Gießen, Beschriften, Drucken_oder_Bedrucken,
	Emaillieren_oder_Glasieren, Färben, Schmelztauchen, Vakuumbedampfen, Vakuumbestäuben, Chemisches_Beschichten,
	Galvanisches_Beschichten, Beschichten_durch_thermisches_Spritzen, Elektrostatisches_Beschichten, Wirbelsintern,
	Spachteln, Auftraghartlöten, Auftragweichlöten, Schmelzauftragschweißen, Fügen_durch_Presspassung, Klammern,
	Klemmen, Nageln_oder_Verstiften_oder_Einschlagen, Schrauben, Verkeilen, Verspannen, Verbindungshartlöten,
	Verbindungsweichlöten, Pressverbindungsschweißen, Schmelzverbindungsschweißen, Fügen_durch_Nietverfahren,
	Fügen_durch_Umformen_bei_Blech_Rohr_und_Profilteilen, Fügen_durch_Umformen_drahtförmiger_Körper, Ausgießen,
	Einbetten, Eingalvanisieren, Kitten, Ummanteln, Vergießen, Einfüllen, Tränken_oder_Imprägnieren,
	Kleben_mit_chemisch_abbindenden_Klebstoffen, Kleben_mit_physikalisch_abbindenden_Klebstoffen, Textiles_Fügen,
	Auflegen_oder_Aufsetzen_oder_Schichten, Einhängen, Einlegen_oder_Einsetzen, Einrenken, Federnd_Einspreizen,
	Ineinanderschieben, Bestrahlen, Magnetisieren, Belichten, Sintern_oder_Brennen, Austenitformhärten,
	Heißisostatisches_Nachverdichten, Verfestigen_durch_Schmieden, Verfestigen_durch_Walzen, Verfestigen_durch_Ziehen,
	Verfestigungsstrahlen, Anlassen_oder_Auslagern, Aushärten, Glühen, Härten, Isothermisches_Umwandeln,
	Thermochemisches_Behandeln, Tiefkühlen, Vergüten, Chemisches_Abtragen, Elektrochemisches_Abtragen,
	Thermisches_Abtragen, Chemisches_Reinigen, Lösemittelreinigen, Mechanisches_Reinigen, Reinigungsstrahlen,
	Strömungstechnisches_Reinigen, Thermisches_Reinigen, Bohren_oder_Senken_oder_Reiben, Bürstenspanen, Drehen,
	Fallen_oder_Raspeln, Fräsen, Hobeln_oder_Stoßen, Räumen, Schaben_oder_Meißeln, Sägen, Bandschleifen, Gleitspanen,
	Honen, Hubschleifen, Läppen, Schleifen_mit_rotierendem_Werkzeug, Strahlspanen, Ablöten, Auseinandernehmen,
	Entleeren, Lösen_kraftschlüssiger_Verbindungen, Lösen_von_Klebeverbindungen, Zerlegen_textiler_Verbindungen,
	Zerlegen_von_durch_Umformen_gefügten_Teilen, Zerlegen_von_durch_Urformen_gefügten_Teilen, Beißschneiden, Brechen,
	Messerschneiden, Reißen, Scherschneiden, Spalten, Biegeumformen_mit_drehender_Werkzeugbewegung,
	Biegeumformen_mit_geradliniger_Werkzeugbewegung, Druckdrücken, Eindrücken, Freiformen, Gesenkformen,
	Oberflächenveredelungsstrahlen, Umformstrahlen, Walzen, Verschieben_mit_drehender_Werkzeugbewegung,
	Verschieben_mit_geradliniger_Werkzeugbewegung, Drücken, Durchziehen, Innenhochdruck_Weitstauchen, Knickbauchen,
	Kragenziehen, Tiefziehen, Längen, Tiefen, Weiten, Gießen_von_Beton_oder_Gips, Gießen_von_Porzellan_oder_Keramik,
	Druckgießen, Niederdruckgießen, Schleudergießen, Schwerkraftgießen, Schäumen, Stranggießen, Tauchformen,
	Urformen_von_faserverstärkten_Kunststoffen, Züchten_von_Kristallen, Abscheiden_aus_der_Dampfphase_in_einer_Form,
	Elektrolytisches_Abscheiden_in_einer_Form, Pressen, Sandformen, Urformen_durch_thermisches_Spritzen, Blasformen,
	Kalandrieren, Modellieren, Pressformen, Spritzgießen, Spritzpressen, Strangpressen, Ziehformen,
	Herstellung_von_Faserplatten, Herstellung_von_Papier_und_Pappe, Herstellung_von_Spanplatten, None;
}
